---
abstract: 'Korean letter conversion'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-KO-Munja
no_index:
  directory:
    - t
    - inc
requires:
  Convert::Moji: 0.03
resources:
  bugtracker: https://github.com/benkasminbullock/Lingua-KO-Munja/issues
  repository: https://github.com/benkasminbullock/Lingua-KO-Munja
version: 0.04
